# Uncomment the next line to define a global platform for your project
platform :ios, '13.2'

target 'smokestack' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for smokestack
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  pod 'Charts'

end
